language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

env:
  - DOCKER_VERSION="1.12.1"

before_install:
  - docker pull elgalu/selenium

script: mvn -Prelease clean verify

after_script:
  - cat ./logs/stdout.zalenium.hub.log
  - cat ./logs/stdout.zalenium.docker.node.log
  - cat ./logs/stdout.zalenium.sauce.node.log
  - docker --version
