language: java
jdk:
  - oraclejdk8

matrix:
  include:
    - os: linux
      language: java
      jdk:
        - oraclejdk8
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.1"
    - os: osx
      language: java
      jdk:
        - oraclejdk8
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.1"

before_install:
  - docker pull elgalu/selenium

script: mvn clean verify
